version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=localhost
      - DB_NAME=database
      - DB_USER=root
      - DB_PASS=
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: